name: Publish on Dockerhub

on:
  push:
    branches:
      - master
    paths:
      - 'VERSION'

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v2

    - name: read version
      id: read
      uses: juliangruber/read-file-action@v1
      with:
        path: ./VERSION

    - name: git tag and push
      run: |
        git tag ${{ steps.read.outputs.content }}
        git push --tags

    - name: Build and push
      run: |
        docker buildx build --platform linux/arm64,linux/amd64 -t franklalalala/dflow_refiner:v${{ steps.read.outputs.content }} --push .
        docker buildx build --platform linux/arm64,linux/amd64 -t franklalalala/dflow_refiner:latest --push .

    - name: Notify deepmodeling
      uses: satak/webrequest-action@master
      with:
        url: https://deepmodeling.com/dflow/apis/op/notify/dockerhub?package_name=dflow_refiner&github_repo=${{ github.repository }}&docker_repo=franklalalala/dflow_refiner
        method: GET
      continue-on-error: true