name: Publish on PyPI

on:
  push:
    branches:
      - master
    paths:
      - 'VERSION'

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: '3.8'

    - name: Install pypa/build
      run: >-
        python -m
        pip install
        build
        --user

    - name: Build a binary wheel and a source tarball
      run: >-
        python -m
        build
        --sdist
        --wheel
        --outdir dist/
        .

    - name: Publish distribution to PyPI
      uses: pypa/gh-action-pypi-publish@master
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}
        verbose: true

    - name: Notify deepmodeling
      uses: satak/webrequest-action@master
      with:
        url: https://deepmodeling.com/dflow/apis/op/notify/pypi?package_name=dflow_refiner&github_repo=${{ github.repository }}
        method: GET
      continue-on-error: true